### ISSUE TITLE
Skipping Directory or File Type no longer working at least in URL mode

### ISSUE THREAD

**Issue by turnerjoy** [felipegiacomozzi/the-trove-downloader#14]
This isn't working for me anymore

There is also and issue for some reason I can't figure out in the https://thetrove.is/Assets/3D/Printing/%20General/ where is always stops after the "Ghost Rider Helmet" folder

**Comment by turnerjoy** [comment]
I just tried 1.07 to see if it still errored and it seems the problem might actually be in the folder after the Ghost Rider Helmet

Loading Page https://thetrove.is/Assets/3D/Printing//%20General//Green%20Lantern/
Checking Item Parent directory/
Checking Item GreenArm1.stl
Checking Item GreenArm2.stl
Checking Item HalJordan_solid.stl
Checking Item JohnStewart_solid.stl
Checking Item Torso-Jordan.stl
Checking Item Torso-Stewart.stl
Checking Item base.stl
Checking Item lef_leg_and_lower_torso.stl
Checking Item left_arm.stl
Error: Error reading item:

**Comment by felipegiacomozzi** [comment]
I just released a new version: https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.10

I found some weird spacer elements that would break the program.
Could you try it out? Thanks!

**Comment by turnerjoy** [comment]
Thanks for the fast reply, that fixed the issue with that one folder. I think there is now an issue with a different folder, if I had to guess it would be because there is a ? in the name, which is not allowed in windows

[10:20:12] Error Downloading Fila j:/t3d\Universal Tile/Universal Tile - 28mm Terrain ?40 Pledge/28mm Universal Tiles/\Tile 3 - Corner.stl. Trying again.
[10:20:12] Downloading File j:/t3d\Universal Tile/Universal Tile - 28mm Terrain ?40 Pledge/28mm Universal Tiles/\Tile 2 - End.stl
[10:20:12] Downloading File j:/t3d\Universal Tile/Universal Tile - 28mm Terrain ?40 Pledge/28mm Universal Tiles/\Tile 3 - Corner.stl
[10:20:12] Error: One or more errors occurred. (One or more errors occurred. (The filename, directory name, or volume label syntax is incorrect. : 'j:\t3d\Universal Tile\Universal Tile - 28mm Terrain ?40 Pledge\28mm Universal Tiles')) (One or more errors occurred. (The filename, directory name, or volume label syntax is incorrect. : 'j:\t3d\Universal Tile\Universal Tile - 28mm Terrain ?40 Pledge\28mm Universal Tiles')) (One or more errors occurred. (The filename, directory name, or volume label syntax is incorrect. : 'j:\t3d\Universal Tile\Universal Tile - 28mm Terrain ?40 Pledge\28mm Universal Tiles'))
[10:20:12]


this is where it is on the site

https://thetrove.is/Assets/3D/Printing/Universal%20Tile/Universal%20Tile%20-%2028mm%20Terrain%20%3F40%20Pledge/

**Comment by felipegiacomozzi** [comment]
Hello @turnerjoy, that`s right. 
I was cleaning up the file names, but not the paths.
Just released a new version fixing this: https://github.com/felipegiacomozzi/the-trove-downloader/releases/tag/1.0.11

Thanks for the report 👍

**Comment by turnerjoy** [comment]
Thanks again. That issue is fixed now. Seems the only other issue seems to be caused by a space at the end; I believe someone else put in a ticket for that also.

It can be seen here with a space after Core Books, don't think that is allowed in Windows:

https://thetrove.is/Books/Basic%20Roleplaying%20%28BRP%29%20%28d100%29/Core%20Books%20/

Message : Could not find a part of the path 'j:\t\Basic Roleplaying (BRP) (d100)\Core Books \Basic RolePlaying (4th Edition).pdf'.

**Comment by turnerjoy** [comment]
Looks like there is also still an issue with ":" as seen here

https://thetrove.is/Tabletop%20Games/BoardGames/Descent%3A%20Journeys%20int%20the%20Dark/


[18:47:30] _basePath: j:/tt/
[18:47:30] _parallel: 55
[18:47:30] _theTroveUrl: https://thetrove.is/Tabletop%20Games/
[18:47:30] ---------------------------------- LAST DOWNLOAD ERROR --------------------------------------
[18:47:30] Error downloading file j:/tt/BoardGames/Descent: Journeys int the Dark/\descent_quests.7z. Trycount: 11.
Exception:System.IO.IOException
Message : The directory name is invalid. : 'j:\tt\BoardGames\Descent: Journeys int the Dark'
StackTrace :    at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at TheTroveDownloader.TheTroveDownloader.CheckIfDirectoryExists(String path)
   at TheTroveDownloader.TheTroveDownloader.DownloadFile(String url, String path)
